services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/data:/config
      - /path/to/data/tvshows:/data/tvshows
      - /path/to/data/movies:/data/movies
      # - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
    #devices:
      #- /dev/dri:/dev/dri #optional
      #- /dev/vchiq:/dev/vchiq #optional
      #- /dev/video10:/dev/video10 #optional
      #- /dev/video11:/dev/video11 #optional
      #- /dev/video12:/dev/video12 #optional
    restart: unless-stopped